docker:
  build: true
  workdir: /app
  ports:
  - "<%= ENV.fetch('RAILS_PORT', 3000)%>:3000"
services:
  mysql:
    compose:
      image: mysql/mysql-server:5.6
      environment:
        MYSQL_ROOT_PASSWORD: <%= ENV.fetch('MYSQL_ROOT_PASSWORD', 'root') %>
scripts:
  start: /app/.testbox/run.sh
  ls: ls
  rails: /app/bin rails
  date: date
  after_checkout: date

feature_flags:
  upcase_titles: false

patches:
  - name: experimental
    operations:
      - op: replace
        path: "services.mysql.compose.image"
        value: "mysql/mysql-server:8.0"
#      - op: remove
#        path: docker.build
#      - op: add
#        path: docker.image
#        value: "gcr.io/toptal-hub/chronicles:latest"
#      - op: add
#        path: docker.entrypoint
#        value: "entrypoint.sh db:download db:migrate graphql:gateway:push graphql:gateway:activate run:all"
